### ISSUE TITLE
One from the 'also ran' section.

### ISSUE THREAD

**Issue by rdebath** [ScoreUnder/brainfuck-interpreter#3]
This is a [cell doubling](http://esolangs.org/wiki/Brainfuck_bitwidth_conversions#Other_Conversions) of the string `+[>]`; as such it should just run straight through. Instead it goes for an infinite loop and tries to use up all of memory.

``` bf
>+<+[>-]>[->>+<]<<
>+<[>-]>[->+>[<-]<[<]>[-<+>]]<-[+<
>>>>
>[-]>[-]<<
>+<[>-]>[->+>[<-]<[<]>[-<+>]]<-]<
```

However, Note that this one completes successfully.

``` bf
>+<+[>-]>[->>+<]<<
>+<[>-]>[->+>[<-]<[<]>[-<+>]]<-[+<
>>>>
>+<[>-]>[->+>[<-]<[<]>[-<+>]]<-]<
```

**Comment by ScoreUnder** [comment]
Thanks again for finding these. Is there a common test suite you're pulling from? I'd like to run as many inputs as possible to see whether there are any more strange behaviours.

**Comment by rdebath** [comment]
You could call it that I suppose; it's actually just all the test programs I found plus a few that I wrote.

https://github.com/rdebath/Brainfuck/blob/master/bitwidth.b
https://github.com/rdebath/Brainfuck/tree/master/testing

The `bitwidth.b` is a bit of a torture test.
Of course, the first test is just a "Hello World!" that is only a little aggressive.

``` bf
>++++++++[-<+++++++++>]<.>[][<-]>+>-[+]++>++>+++[>[->+++<<+++>]<<]>-----.
>->+++..+++.>-.<<+[>[+>+]>>]<--------------.>>.+++.------.--------.>+.>+.
```

You seem to be successful at all you're fast enough for at the moment: 
https://rawgit.com/rdebath/Brainfuck/results/index.html
